name: Proposal Assistant
region: nyc1

services:
  - name: backend
    github:
      repo: Zenovo-AI/proposal_agents
      branch: main
    run_command: uvicorn main:app --host 0.0.0.0 --port 8080
    http_port: 8080
    ingress:
      rules:
        - match:
            path:
              prefix: /api/
          component:
            name: backend
          cors:
            allow_origins:
              - exact: https://cdga-proposal-agent-r2v7y.ondigitalocean.app
            allow_methods: ["GET", "POST", "OPTIONS"]
            allow_headers: ["*"]
            expose_headers: ["*"]
            allow_credentials: true
            max_age: 86400
    deploy_on_push: true
    instance_count: 1
    instance_size_slug: basic-xxs
